# Generated by Django 5.0.2 on 2024-05-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='priceOfPack',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
