# Generated by Django 5.0.2 on 2024-05-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_user_priceofpack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='amountCigarettesInPack',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='progressDays',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
